gcs_contents_manager.py
=> Remove version from KMS Key Name for compatibility with CMEK buckets

README.md, jupyterlab_gcedetails/package.json, jupyterlab_gcpscheduler/package.json, jupyterlab_gcsfilebrowser/package.json
- Add private indicator to each NPM package to ensure they
are not published apart from their required Python package.
- Fix bug in jupyterlab_gcedetails package.json
=> Update README with more detailed development instructions.

jupyterlab_gcpscheduler/package-lock.json, jupyterlab_gcpscheduler/package.json, jupyterlab_gcpscheduler/schema/gcpsettings.json, jupyterlab_gcpscheduler/src/components/__snapshots__/job_list_item.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/__snapshots__/jobs_panel_widget.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/__snapshots__/submitted_job.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/dialog.tsx, jupyterlab_gcpscheduler/src/components/job_list_item.spec.tsx, jupyterlab_gcpscheduler/src/components/job_list_item.tsx, jupyterlab_gcpscheduler/src/components/jobs_panel_widget.tsx, jupyterlab_gcpscheduler/src/components/scheduler_form.spec.tsx, jupyterlab_gcpscheduler/src/components/scheduler_form.tsx, jupyterlab_gcpscheduler/src/components/submitted_job.spec.tsx, jupyterlab_gcpscheduler/src/components/submitted_job.tsx, jupyterlab_gcpscheduler/src/data.ts, jupyterlab_gcpscheduler/src/index.ts, jupyterlab_gcpscheduler/src/service/gcp.spec.ts, jupyterlab_gcpscheduler/src/service/gcp.ts, package-lock.json
Moved over some changes from git-on-borq post migration. Also had to recreate some snapshots.
=> Final Changes from git-on-borg

.github/workflows/presubmit.yaml, jupyterlab_gcedetails/jest.config.js, jupyterlab_gcedetails/package.json, jupyterlab_gcpscheduler/jest.config.js, jupyterlab_gcpscheduler/package.json, jupyterlab_gcsfilebrowser/jest.config.js, jupyterlab_gcsfilebrowser/package.json, shared/client/jest.config.js, shared/client/package.json
=> Add presubmit GitHub action to build and run all tests

package-lock.json, package.json
Adds the `husky` [npm package](https://www.npmjs.com/package/husky) to run scripts on git hooks. Currently, husky will run the linter on all packages before committing and will run the linter and tests before a push.
=> feat: add husky git hooks and lerna lint script

jupyterlab_comments/README.md, jupyterlab_comments/jupyterlab_comments/__init__.py, jupyterlab_comments/jupyterlab_comments/git_commands.py, jupyterlab_comments/jupyterlab_comments/handlers.py, jupyterlab_comments/src/components/comments_widget.tsx, jupyterlab_comments/src/git.ts, jupyterlab_comments/src/index.ts, jupyterlab_comments/src/service/file.ts
Add ability to get the currently open file and fetch detached comments for that file
=> Fetch detached comments for a file

shared/package.json, shared/src/components/context_menu.tsx, shared/src/index.ts
- exporting radio input component
- stopping propagation on the context menu component
=> update to shared components

jupyterlab_comments/src/components/comment.tsx, jupyterlab_comments/src/components/comments_widget.tsx, jupyterlab_comments/src/index.ts, jupyterlab_comments/src/service/comment.ts
- Add separate interface for code review comments
- Update UI to display the two types of comments on separate tabs
=> Display review comments

jupyterlab_gcedetails/package-lock.json, jupyterlab_gcedetails/package.json, jupyterlab_gcedetails/src/components/hardware_scaling_dialog.tsx, jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx, jupyterlab_gcedetails/src/components/input_slider.tsx, jupyterlab_gcedetails/src/components/synchronized_sliders.tsx, jupyterlab_gcedetails/src/data.ts, shared/package.json, shared/src/components/text_input.tsx
Creating UI for the Hardware Scaling form dialog that allows a user to modify the hardware configuration for their notebook.
This commit includes:
- Implementing a SynchronizedSliders component which creates two sliders with text input which can only take on values defined by an array of objects passed as props. The object contains a cpu key which represents the value the first slider can take and a memory key which represent the value the second slider will take consequently and vice versa. This forces the sliders to stay in sync with one another.
- Implementing a HardwareScalingForm component which allows a user to select a machine type, CPU value, memory value and GPU type.
- Implementing a HardwareScalingDialog component which is a dialog thinly wrapping over HardwareScalingForm.
- …
=> [HardwareConfiguration] Created hardware scaling form and dialog

jupyterlab_bigquery/jupyterlab_bigquery/__init__.py, jupyterlab_bigquery/jupyterlab_bigquery/handlers.py, jupyterlab_bigquery/jupyterlab_bigquery/pagedAPI_handler/__init__.py, jupyterlab_bigquery/jupyterlab_bigquery/pagedAPI_handler/pagedAPI_handler.py, jupyterlab_bigquery/jupyterlab_bigquery/pagedAPI_handler/pagedQuery_handler.py
Provides backend support for Paged API
=> [BigQuery] Paged API backend support

jupyterlab_bigquery/jupyterlab_bigquery/handlers.py, jupyterlab_bigquery/package-lock.json, jupyterlab_bigquery/package.json, jupyterlab_bigquery/setup.py, jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx, jupyterlab_bigquery/src/components/list_items_panel/list_tree_item_widget.tsx, jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx, jupyterlab_bigquery/src/components/list_items_panel/service/list_items.ts, jupyterlab_bigquery/src/index.ts, jupyterlab_bigquery/src/reducers/dataTreeSlice.ts, jupyterlab_bigquery/src/reducers/index.ts, jupyterlab_bigquery/src/utils/widget_manager.ts, package-lock.json
Refactor side panel data tree to use redux and material-tree
=> [BigQuery] Refactor data tree

jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx, jupyterlab_bigquery/src/components/list_items_panel/list_tree_item_widget.tsx
Create a context menu for Data Tree elements and fix click propagation issues
=> [BigQuery] Create context menu

jupyterlab_bigquery/src/components/details_panel/details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/table_details_panel.tsx
Makes it possible to see large table schema by scrolling.
=> [BigQuery] Scroll for long table schema

jupyterlab_comments/README.md, jupyterlab_comments/jupyterlab_comments/__init__.py, jupyterlab_comments/jupyterlab_comments/git_commands.py, jupyterlab_comments/jupyterlab_comments/handlers.py, jupyterlab_comments/jupyterlab_comments/refresh.py, jupyterlab_comments/src/components/comments_widget.tsx, jupyterlab_comments/src/service/request.ts
- Add configurable traitlet for the refresh interval
- Add handler to fetch the configured value
- Add handler to invoke 'git appraise pull' to fetch new comments from the configured remote
- Add setInterval() to invoke the remote fetch handler
- Fix getters for detached and review comments so that the UI will refresh even when the file clicked on has no comments
=> Automatic refresh

jupyterlab_gcedetails/src/components/machine_type_select.tsx, jupyterlab_gcedetails/src/data.ts
Adding NestedSelect component which allows a user to select a machine type.
=> [HardwareConfiguration] Adding machine type drop down select component

jupyterlab_bigquery/jupyterlab_bigquery/__init__.py, jupyterlab_bigquery/jupyterlab_bigquery/handlers.py, jupyterlab_bigquery/src/components/details_panel/service/list_table_details.ts, jupyterlab_bigquery/src/components/details_panel/table_details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx, jupyterlab_bigquery/src/components/details_panel/table_preview.tsx
Adds table preview under the `preview` tab in the table details window.
=> [BigQuery] Table preview

jupyterlab_bigquery/jupyterlab_bigquery/__init__.py, jupyterlab_bigquery/jupyterlab_bigquery/pagedAPI_handler/pagedQuery_handler.py, jupyterlab_bigquery/jupyterlab_bigquery/query_incell_editor.py, jupyterlab_bigquery/src/components/query_editor/query_editor_incell/query_editor_incell.tsx, jupyterlab_bigquery/src/components/query_editor/query_editor_incell/query_editor_incell_widget.tsx, jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx, jupyterlab_bigquery/src/index.ts
IPython magic for incell editor
- load query from cell into query editor
- bug fix: error for empty query
- query editor check SQL query on load
- communication between python and TS
=> [BigQuery] IPython magic for incell editor

jupyterlab_bigquery/jupyterlab_bigquery/details_handler/details_handler.py, jupyterlab_bigquery/src/components/details_panel/dataset_details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx, jupyterlab_bigquery/src/components/details_panel/table_preview.tsx, jupyterlab_bigquery/src/components/query_editor/query_editor_incell/query_editor_incell.tsx, jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_results.tsx, jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab.tsx, jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx, jupyterlab_bigquery/src/components/shared/bq_table.tsx, jupyterlab_bigquery/src/components/shared/header.tsx
Creates a new shared `Header` and `BQTable` component that can be used across the extension.
=> [BigQuery] Shared table and header styles

jupyterlab_bigquery/jupyterlab_bigquery/list_items_handler/list_items_handler.py, jupyterlab_bigquery/jupyterlab_bigquery/list_items_handler/service.py, jupyterlab_bigquery/jupyterlab_bigquery/tests/list_items_service_test.py, jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx, jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx, jupyterlab_bigquery/src/components/list_items_panel/service/list_items.ts, jupyterlab_bigquery/src/reducers/dataTreeSlice.ts
Create pinning button and dialog. Currently has basic error displays in the data tree. Next PR will have a snackbar component added to display errors. Testing will also be included in next PR.
=> [BigQuery] Create pinning dialog

jupyterlab_comments/jupyterlab_comments/__init__.py, jupyterlab_comments/jupyterlab_comments/git_commands.py, jupyterlab_comments/jupyterlab_comments/handlers.py, jupyterlab_comments/src/components/comment.tsx, jupyterlab_comments/src/components/comments_widget.tsx, jupyterlab_comments/src/components/reply_editor.tsx, jupyterlab_comments/src/components/start_thread.tsx, jupyterlab_comments/src/index.ts, jupyterlab_comments/src/service/add_comment.ts, jupyterlab_comments/src/service/comment.ts, jupyterlab_comments/src/service/jupyterConfig.ts, jupyterlab_comments/src/test/__snapshots__/component.test.tsx.snap, jupyterlab_comments/src/test/component.test.tsx
- Handler for adding new detached comments and pushing them to the remote repo
- Additional components: TextField for starting a new comment thread; expandable TextField for replying to a specific comment
=> Add comments handler

jupyterlab_gcedetails/src/components/hardware_scaling_dialog.tsx, jupyterlab_gcedetails/src/data.ts
Quick PR to add the view state variable to the HardwareScalingDialog so we can display different pages in the dialog.
=> [HardwareConfiguration] Adding state to hardware scaling dialog

jupyterlab_bigquery/jupyterlab_bigquery/pagedAPI_handler/pagedQuery_handler.py, jupyterlab_bigquery/jupyterlab_bigquery/query_incell_editor.py, jupyterlab_bigquery/jupyterlab_bigquery/tests/pagedAPI_handler/pagedQuery_handler_test.py, jupyterlab_bigquery/src/components/query_editor/query_editor_incell/query_editor_incell.tsx, jupyterlab_bigquery/src/components/query_editor/query_editor_incell/query_editor_incell_widget.tsx, jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx
Support for the following flags: `project`, `maximum_bytes_billed`,  `params`, `use_legacy_sql`
=> [BigQuery] support for incell editor flags

jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx
=> [BigQuery] syntax debug highlight

jupyterlab_caip_optimizer/src/components/create_study.spec.tsx, jupyterlab_caip_optimizer/src/components/create_study.tsx, jupyterlab_caip_optimizer/src/components/dashboard.spec.tsx, jupyterlab_caip_optimizer/src/components/study_details.spec.tsx, jupyterlab_caip_optimizer/src/service/test-constants.ts, jupyterlab_caip_optimizer/src/utils/redux_render.tsx, jupyterlab_caip_optimizer/src/utils/urls.ts
- Adds tests for the create study page
- Adds tests for the study details page
=> [Optimizer] add create study and study details tests

jupyterlab_bigquery/jupyterlab_bigquery/list_items_handler/service.py, jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx, package-lock.json
Change searching to search all pinned projects in the data tree. Update the 'enable Data Catalog API' dialog to appear when searching returns an error.
=> [BigQuery] Search all pinned projects

jupyterlab_bigquery/jupyterlab_bigquery/__init__.py, jupyterlab_bigquery/jupyterlab_bigquery/details_handler/__init__.py, jupyterlab_bigquery/jupyterlab_bigquery/details_handler/details_handler.py, jupyterlab_bigquery/jupyterlab_bigquery/tests/details_handlers_test.py, jupyterlab_bigquery/src/components/details_panel/details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/service/list_view_details.ts, jupyterlab_bigquery/src/components/details_panel/table_details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/view_details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/view_details_widget.tsx, jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx
Allows a user to double click on a view in the data tree and open a View Details panel with a formatted query.
=> [BigQuery] Add view details

jupyterlab_caip_optimizer/src/components/create_study/index.spec.tsx, jupyterlab_caip_optimizer/src/components/create_study/index.tsx, jupyterlab_caip_optimizer/src/components/create_study/metric_list.tsx, jupyterlab_caip_optimizer/src/components/create_study/parameter_list.tsx, jupyterlab_caip_optimizer/src/components/create_study/parameter_type_inputs.tsx, jupyterlab_caip_optimizer/src/components/misc/ChipBox.tsx
- **Should I use that particular icon?**
- I also reworked how we are storing the temporary parameters. This should make it easier to get conditional parameters working with create study.
- I also cleaned up the tests by creating some helper functions to create parameters and metrics.
- **Overview:**
- **Double:**
- **Integer:**
- **Discrete:**
- **Categorical:**
=> [Optimizer] update create study's looks

jupyterlab_gcedetails/src/details_widget.tsx
A quick bugfix for the instance name parsing
=> [HardwareConfiguration] Bugfix/instance name split

jupyterlab_comments/jupyterlab_comments/__init__.py, jupyterlab_comments/jupyterlab_comments/git_commands.py, jupyterlab_comments/jupyterlab_comments/handlers.py, jupyterlab_comments/jupyterlab_comments/tests/handlers_test.py, jupyterlab_comments/jupyterlab_comments/tests/test_helpers.py, jupyterlab_comments/src/components/code_review.tsx, jupyterlab_comments/src/components/comment.tsx, jupyterlab_comments/src/components/comments_widget.tsx, jupyterlab_comments/src/components/reply_editor.tsx, jupyterlab_comments/src/components/start_thread.tsx, jupyterlab_comments/src/service/add_comment.ts, jupyterlab_comments/src/service/comment.ts, jupyterlab_comments/src/test/__snapshots__/component.test.tsx.snap, jupyterlab_comments/src/test/component.test.tsx
- Change request handler for fetching review comments to fetch comments from all open code reviews, not just the current review
- Add request handlers for adding new review comment thread and adding new review reply comment
- Update UI to display review comments from the same code review in the same section
- Add comment editor for new review comment thread
=> Adding review comments

jupyterlab_gcedetails/jupyterlab_gcedetails/handlers.py, jupyterlab_gcedetails/jupyterlab_gcedetails/handlers_test.py, jupyterlab_gcedetails/jupyterlab_gcedetails/test_data.py, jupyterlab_gcedetails/src/data.ts
Retrieves accelerator types from gcloud command line on the VM the notebook is running on.
=> [HardwareConfiguration] Fetching accelerator types from gcloud

jupyterlab_gcedetails/src/components/resource_utilization_charts.tsx
Here's how it currently looks, let me know if there are any styling changes I should make.
=> Added gpu graphs

jupyterlab_bigquery/src/components/details_panel/details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/model_details_panel.tsx, package-lock.json
Styles details chips blue according to the mocks, and fixes model details panel so it is scrollable.
=> [BigQuery] Details chips styling and model details scroll

jupyterlab_bigquery/jupyterlab_bigquery/details_handler/details_handler.py, jupyterlab_bigquery/jupyterlab_bigquery/tests/details_handlers_test.py, jupyterlab_bigquery/package.json, jupyterlab_bigquery/src/components/details_panel/dataset_details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/model_details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/table_details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/view_details_panel.tsx, jupyterlab_bigquery/src/utils/formatters.ts, package-lock.json
Uses [luxon](https://moment.github.io/luxon/index.html), a [successor](https://moment.github.io/luxon/docs/manual/why.html) of [moment](https://momentjs.com/) to detect the user's timezone and apply it. This is done in a new `formatters` file under the `utils` folder.
Updated python tests as well since the date is now passed as an ISO format string rather than a pre-formatted date string.
=> [BigQuery] Display dates and times according to user timezone

jupyterlab_automl/src/components/automl_widget.tsx, jupyterlab_automl/src/components/import_data.tsx, jupyterlab_automl/src/components/import_model.tsx, jupyterlab_automl/src/components/list_resources_panel.tsx, shared/src/components/action_bar.tsx, shared/src/components/dialog.tsx
- Import/export data dialog maintains a single height despite toggle
- Changed button color in ListResourcesPanel toolbar to match surrounding icons
- Added tooltips to ListResourcesPanel
=> [uCAIP] smaller UI fixes

jupyterlab_comments/README.md, jupyterlab_comments/package.json, jupyterlab_comments/src/components/code_review.tsx, jupyterlab_comments/src/components/comments_widget.tsx, jupyterlab_comments/src/components/reply_editor.tsx, jupyterlab_comments/src/components/send_button.tsx, jupyterlab_comments/src/components/start_thread.tsx, jupyterlab_comments/src/service/timestamp.ts, jupyterlab_comments/src/test/__snapshots__/component.test.tsx.snap, jupyterlab_comments/src/test/component.test.tsx
- change how small timestamps are displayed
- update setup instructions
- display more info for a code review
- refactor thread and reply comment editors to remove duplicate code
- add icons
=> Commenting ui

shared/src/components/action_bar.tsx
- fixes problem with overlap in the dialogs
=> removed action bar attach to bottom

jupyterlab_bigquery/jupyterlab_bigquery/details_handler/details_handler.py, jupyterlab_bigquery/jupyterlab_bigquery/tests/details_handlers_test.py, jupyterlab_bigquery/package-lock.json, jupyterlab_bigquery/src/components/details_panel/model_details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/service/list_view_details.ts, jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx, jupyterlab_bigquery/src/components/details_panel/view_details_panel.tsx, jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx, package-lock.json
Allows user to open a new full-window editor with a starter query from the view and model details pages.
=> [BigQuery] Open query editor from view and model details

jupyterlab_gitsync/src/index.ts, jupyterlab_gitsync/src/service/file.ts, jupyterlab_gitsync/src/service/notebook_file.ts, jupyterlab_gitsync/src/service/notebook_resolver.ts, jupyterlab_gitsync/src/service/resolver.ts, jupyterlab_gitsync/src/service/service.ts, jupyterlab_gitsync/src/service/tracker.ts
* add dirty state listener on service needed for status indicator
* change tracker implementation to use general interface objects
* add save after merge to reduce chances of bugs
* add outline for NotebookFile and NotebookResolver classes
=> [GitSync] add outline for notebook sync

jupyterlab_caip_optimizer/package-lock.json, jupyterlab_comments/package-lock.json, jupyterlab_gcedetails/package-lock.json, jupyterlab_gcedetails/package.json, jupyterlab_gcedetails/src/e2e/integration.test.ts, jupyterlab_gcpscheduler/package-lock.json, jupyterlab_gcsfilebrowser/package-lock.json, package-lock.json, shared/package-lock.json
Adds missing types package and updates test to include new scenarios.
=> [HardwareConfig] Update package.json and E2E test

jupyterlab_comments/README.md, jupyterlab_comments/jupyterlab_comments/git_commands.py, jupyterlab_comments/jupyterlab_comments/handlers.py, jupyterlab_comments/package.json, jupyterlab_comments/src/components/code_review.tsx, jupyterlab_comments/src/components/comment.tsx, jupyterlab_comments/src/components/comment_context.tsx, jupyterlab_comments/src/components/comments_widget.tsx, jupyterlab_comments/src/components/start_thread.tsx, jupyterlab_comments/src/index.ts, jupyterlab_comments/src/service/add_comment.ts, jupyterlab_comments/src/service/file.ts, jupyterlab_comments/src/test/__snapshots__/component.test.tsx.snap
working on display comment context for notebook files in a future PR
=> Comment context for non-notebook files

package-lock.json
Removed the pip environment then reinstalled the gcedetails_extension and shared module following the instructions outlined in the root of the repo.
=> Package lock updates after reinstalling pipenv

jupyterlab_gcedetails/package-lock.json, jupyterlab_gcedetails/package.json, package-lock.json
Adding missing material-ui dependency to the gcedetails package file
=> [HardwareConfiguration] Adding material UI dependency

jupyterlab_gcedetails/src/data/accelerator_types.spec.ts, jupyterlab_gcedetails/src/data/accelerator_types.ts
Adding unit tests to cover the accelerator type conversion methods found in the data/accelerator_types.ts file
=> [HardwareConfiguration] Adding tests for accelerator type conversion methods

jupyterlab_bigquery/jupyterlab_bigquery/__init__.py, jupyterlab_bigquery/jupyterlab_bigquery/details_handler/__init__.py, jupyterlab_bigquery/jupyterlab_bigquery/details_handler/details_handler.py, jupyterlab_bigquery/jupyterlab_bigquery/tests/details_handlers_test.py, jupyterlab_bigquery/src/components/details_panel/dataset_details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/model_details_panel.tsx, jupyterlab_bigquery/src/components/details_panel/service/list_model_details.ts, jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx, jupyterlab_bigquery/src/components/details_panel/view_details_panel.tsx, jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_editor_results.tsx, jupyterlab_bigquery/src/components/query_history/query_history_panel.tsx, jupyterlab_bigquery/src/components/shared/header.tsx
Adds a dropdown for training runs if there are multiple, and makes training options visible.
Also refactors the shared header to account for the dropdown which is located there.
=> [BigQuery] Dropdown for training runs, training options

jupyterlab_gcedetails/src/components/error_page.tsx, jupyterlab_gcedetails/src/components/hardware_configuration_dialog.tsx, jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx, jupyterlab_gcedetails/src/components/hardware_scaling_status.tsx, jupyterlab_gcedetails/src/data/data.ts, jupyterlab_gcedetails/src/data/machine_types.spec.ts, jupyterlab_gcedetails/src/data/machine_types.ts, jupyterlab_gcedetails/src/details_widget.tsx, jupyterlab_gcedetails/src/test_helpers.ts
Adding unit tests for the conversion methods found under data/machine_type.ts
=> [HardwareConfiguration] Adding tests for machine type data methods

jupyterlab_bigquery/jupyterlab_bigquery/query_history_handler/query_history_handler.py, jupyterlab_bigquery/src/components/query_history/query_history_panel.tsx, jupyterlab_bigquery/src/components/query_history/service/query_history.ts
Allow refresh for query history
=> [BigQuery] Query history refresh button

jupyterlab_gitsync/src/service/file.ts, jupyterlab_gitsync/src/service/nbmerge_api.ts, jupyterlab_gitsync/src/service/notebook_file.ts, jupyterlab_gitsync/src/service/notebook_resolver.ts, jupyterlab_gitsync/src/service/resolver.ts, jupyterlab_gitsync/src/service/tracker.ts
* implement algorithm for merging notebook files
=> [GitSync] add nbmerge api

jupyterlab_gcedetails/jupyterlab_gcedetails/__init__.py, jupyterlab_gcedetails/jupyterlab_gcedetails/handlers.py, jupyterlab_gcedetails/src/components/hardware_configuration_dialog.tsx, jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx, jupyterlab_gcedetails/src/components/instance_details_message.tsx, jupyterlab_gcedetails/src/data/data.ts, jupyterlab_gcedetails/src/details_widget.spec.tsx, jupyterlab_gcedetails/src/details_widget.tsx, jupyterlab_gcedetails/src/service/details_service.ts, jupyterlab_gcedetails/src/service/notebooks_service.ts, jupyterlab_gcedetails/src/service/price_service.ts
Adding PriceService which creates a map of  Compute Resource SKU's to the resource cost and uses it to calculate an estimation of the monthly cost of a particular instance. The estimated monthly cost for an instance is then displayed in the hardware scaling form under a 'Pricing Estimation' section:
https://screencast.googleplex.com/cast/NjMwMzc0NjA0MjYyNjA0OHwyOWE0OGEzOS1mOQ
Will add tests in next PR.
=> [HardwareConfiguration] Adding cost estimation

jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx, jupyterlab_gcedetails/src/service/details_service.spec.ts, jupyterlab_gcedetails/src/service/price_service.spec.ts, jupyterlab_gcedetails/src/service/price_service.ts
Adding test for getPrice method of PriceService.
=> [HardwareConfiguration] Adding tests for PriceService

jupyterlab_gcedetails/jupyterlab_gcedetails/handlers.py, jupyterlab_gitsync/src/service/nbmerge_api.ts, jupyterlab_gitsync/src/service/notebook_resolver.ts, jupyterlab_ucaip/jupyterlab_ucaip/public.py, jupyterlab_ucaip/jupyterlab_ucaip/tests/handlers_test.py, jupyterlab_ucaip/setup.py, package-lock.json, scripts/run_all_tests.sh
=> Linting and formatting for all packages

jupyterlab_bigquery/jupyterlab_bigquery/__init__.py, jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx, jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab.tsx, jupyterlab_bigquery/src/index.ts, jupyterlab_bigquery/src/utils/widgetManager/widget_manager.ts
There are two parts to incell editor: DOMWidget(python) and IpywidgetRegistry(front).
No both / Yes front, no python:
No front, Yes python
=> [BigQuery] In cell fail safe

jupyterlab_gcedetails/src/components/__snapshots__/hardware_scaling_form.spec.tsx.snap, jupyterlab_gcedetails/src/components/hardware_scaling_form.spec.tsx, jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx
Adding test file to cover main user flows for the HardwareScalingForm component.
=> [HardwareConfiguration] Adding tests for HardwareScalingForm

jupyterlab_gcedetails/src/components/__snapshots__/hardware_configuration_dialog.spec.tsx.snap, jupyterlab_gcedetails/src/components/details_dialog_body.tsx, jupyterlab_gcedetails/src/components/hardware_configuration_dialog.spec.tsx, jupyterlab_gcedetails/src/components/hardware_configuration_dialog.tsx, jupyterlab_gcedetails/src/components/hardware_scaling_form.spec.tsx, jupyterlab_gcedetails/src/test_helpers.ts
Adding basic tests for Hardware Configuration Dialog
=> [HardwareConfiguration] Adding tests for Hardware Configuration Dialog

jupyterlab_gcedetails/README.md, jupyterlab_gcedetails/src/components/__snapshots__/hardware_scaling_form.spec.tsx.snap, jupyterlab_gcedetails/src/components/chart_wrapper.tsx, jupyterlab_gcedetails/src/components/confirmation_page.tsx, jupyterlab_gcedetails/src/components/details_dialog_body.tsx, jupyterlab_gcedetails/src/components/error_page.tsx, jupyterlab_gcedetails/src/components/hardware_configuration_description.tsx, jupyterlab_gcedetails/src/components/hardware_configuration_dialog.spec.tsx, jupyterlab_gcedetails/src/components/hardware_configuration_dialog.tsx, jupyterlab_gcedetails/src/components/hardware_scaling_form.spec.tsx, jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx, jupyterlab_gcedetails/src/components/hardware_scaling_status.spec.tsx, jupyterlab_gcedetails/src/components/hardware_scaling_status.tsx, jupyterlab_gcedetails/src/components/instance_details_message.tsx, jupyterlab_gcedetails/src/components/resource_utilization_charts.tsx, jupyterlab_gcedetails/src/components/server_wrapper.tsx, jupyterlab_gcedetails/src/data/machine_types.spec.ts, jupyterlab_gcedetails/src/details_widget.spec.tsx, jupyterlab_gcedetails/src/details_widget.tsx, jupyterlab_gcedetails/src/index.ts, jupyterlab_gcedetails/src/service/auth_token_retrieval.spec.ts, jupyterlab_gcedetails/src/service/auth_token_retrieval.ts, jupyterlab_gcedetails/src/service/details_service.spec.ts, jupyterlab_gcedetails/src/service/notebooks_service.spec.ts
This PR:
- Improves code hygiene: more consistent order of imports/props, function names, spacing, adding copyright message
- Updates the labels on the hardware configuration form and confirmation page
- Updates the README
=> [HardwareConfiguration] Improving code readability, updating labels, snapshots and README

jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx, jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx, jupyterlab_gcpscheduler/src/components/__snapshots__/submitted_job.spec.tsx.snap, shared/gcp_jupyterlab_shared/__init__.py, shared/package.json, shared/src/components/dialog.tsx, shared/src/components/submit_button.tsx, shared/src/styles.ts
Adapts the shared `Dialog` and `SubmitButton` for dark mode.
=> [BigQuery] Dark mode for dialog, submit button

jupyterlab_bigquery/src/components/query_history/query_bar.tsx, jupyterlab_bigquery/src/components/query_history/query_details.tsx, jupyterlab_bigquery/src/components/query_history/query_history_panel.tsx, jupyterlab_bigquery/src/components/query_history/query_status_bar.tsx
Moves `QueryDetails`, `QueryBar`, and `QueryStatus` to their own files.
=> [BigQuery] Move query history components to their own files

jupyterlab_bigquery/src/components/details_panel/model_details_panel.spec.tsx, jupyterlab_bigquery/src/components/details_panel/model_details_panel.tsx
Simple check for presence of training run dropdown according to the number of training runs set in the details state.
=> [BigQuery] Testing presence of training run dropdown

jupyterlab_bigquery/jupyterlab_bigquery/pagedAPI_handler/pagedQuery_handler.py, jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_editor_results.tsx, jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx, jupyterlab_bigquery/src/index.ts, jupyterlab_bigquery/src/reducers/queryEditorTabSlice.ts, jupyterlab_bigquery/src/utils/widgetManager/widget_manager.ts
- Added query time elapsed and export as data frame option
=> [BigQuery] UI updates

jupyterlab_bigquery/jupyterlab_bigquery/version.py, jupyterlab_bigquery/package.json, jupyterlab_bigquery/src/index.ts
Depends on https://github.com/GoogleCloudPlatform/jupyter-extensions/pull/349
=> [BigQuery] Bump version to 0.1.1

jupyterlab_gitsync/src/components/git_setup/path_setup.tsx, jupyterlab_gitsync/src/components/log.tsx, jupyterlab_gitsync/src/components/log_panel/file_conflicts.tsx, jupyterlab_gitsync/src/components/log_panel/index.ts, jupyterlab_gitsync/src/components/log_panel/sync_log.tsx, jupyterlab_gitsync/src/components/toolbar_buttons/status_button.tsx, jupyterlab_gitsync/src/index.ts, jupyterlab_gitsync/src/service/git.ts, jupyterlab_gitsync/src/service/notebook_file.ts, jupyterlab_gitsync/src/service/notebook_resolver.ts, jupyterlab_gitsync/src/service/service.ts, jupyterlab_gitsync/src/service/text_file.ts, jupyterlab_gitsync/src/service/text_resolver.ts
**UI Components**
- Added conflict state for status indicator, dialog popup on conflict, and file list for displaying conflicts in files
- Add revert disk method so that remote changes do not overwrite local changes when conflicts occur
**Bug Fixes**
- change file save to a context save to avoid save warning when user manually saves files
- change initial comparison to compare base and remote so that merging occurs only when needed
=> [Git Sync] Add file conflicts UI component & minor bug fixes

jupyterlab_gcsfilebrowser/jupyterlab_gcsfilebrowser/version.py, jupyterlab_gcsfilebrowser/package.json, jupyterlab_gcsfilebrowser/src/index.ts, jupyterlab_gcsfilebrowser/src/panel_header.tsx, shared/gcp_jupyterlab_shared/__init__.py, shared/gcp_jupyterlab_shared/handlers.py, shared/gcp_jupyterlab_shared/handlers_test.py, shared/gcp_jupyterlab_shared/version.py, shared/package.json, shared/setup.py, shared/src/components/badge.tsx
- Bumps shared version number and structures the version file in the same
manner as other packages.
=> Adds Alpha badge to GCS Filebrowser extension.

jupyterlab_gcsfilebrowser/jupyterlab_gcsfilebrowser/handlers.py, jupyterlab_gcsfilebrowser/jupyterlab_gcsfilebrowser/tests/handlers_test.py, jupyterlab_gcsfilebrowser/jupyterlab_gcsfilebrowser/version.py, jupyterlab_gcsfilebrowser/package.json, package-lock.json
=> [GCS Filebrowser] Fix issue #315 of failing to allow empty folders to be browsed

jupyterlab_bigquery/jupyterlab_bigquery/version.py, jupyterlab_bigquery/package.json, jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx, jupyterlab_bigquery/src/components/query_editor/query_editor_incell/query_editor_incell.spec.tsx, jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab.spec.tsx, jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_editor_results.spec.tsx, jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx, jupyterlab_bigquery/src/utils/MockQueryResultsManager.ts
=> Add Alpha badge to BigQuery, Bump version to 0.1.2, and fix failing test

jupyterlab_vizier/src/service/vizier_service.ts, package-lock.json
I don't know why I have like 3 of the same commits
=> Fix vizier service

Pipfile.lock, jupyterlab_hwconfig/README.md, jupyterlab_hwconfig/jupyterlab_hwconfig/version.py, jupyterlab_hwconfig/package.json, jupyterlab_hwconfig/src/components/__snapshots__/hardware_scaling_status.spec.tsx.snap, jupyterlab_hwconfig/src/components/action_bar.tsx, jupyterlab_hwconfig/src/components/details_dialog_body.tsx, jupyterlab_hwconfig/src/components/error_page.tsx, jupyterlab_hwconfig/src/components/hardware_scaling_status.tsx, jupyterlab_hwconfig/src/data/data.ts, jupyterlab_hwconfig/src/details_widget.spec.tsx, jupyterlab_hwconfig/src/service/notebooks_service.ts, jupyterlab_hwconfig/src/test_helpers.ts, scripts/deploy.sh
- Add GPU model and count information to displayed attributes
- Move to v1 endpoint for Notebooks API
- Change Update button to Modify hardware
**Screenshots:**
- New Details dialog
- ![Bdwd2fY78MsED2w](https://user-images.githubusercontent.com/6835846/96506157-2b088280-1225-11eb-9d7b-fd84318d0b46.png)
- Modified dialog warning
- ![3VwvRiZVxpm2vMA](https://user-images.githubusercontent.com/6835846/96506233-4a071480-1225-11eb-9648-7bc450b80680.png)
=> [HWConfig] UX improvements and fixes

jupyterlab_bigquery/jupyterlab_bigquery/version.py, jupyterlab_bigquery/package.json, jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx, jupyterlab_bigquery/src/components/list_items_panel/service/list_items.ts, jupyterlab_bigquery/src/reducers/dataTreeSlice.ts, package-lock.json
This change will ensure that the `bigquery-public-data` project is always pinned as the first item in the resources list.
[Screencast](https://screencast.googleplex.com/cast/NTc0OTU2ODkwODAzNDA0OHw1MmYyYmNjYi1hNQ)
=> Pin the bigquery-public-data project in the BQ extension

jupyterlab_gcpscheduler/src/components/__snapshots__/dialog.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/__snapshots__/job_list_item.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/__snapshots__/jobs_panel_widget.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/__snapshots__/share_dialog.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/__snapshots__/submitted_job.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/dialog.tsx, jupyterlab_gcpscheduler/src/components/job_list_item.spec.tsx, jupyterlab_gcpscheduler/src/components/job_list_item.tsx, jupyterlab_gcpscheduler/src/components/jobs_panel_widget.spec.tsx, jupyterlab_gcpscheduler/src/components/jobs_panel_widget.tsx, jupyterlab_gcpscheduler/src/components/schedule_builder/__snapshots__/cron_schedule_form.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/schedule_builder/cron_schedule_form.tsx, jupyterlab_gcpscheduler/src/components/schedule_builder/week_schedule_form.spec.tsx, jupyterlab_gcpscheduler/src/components/schedule_builder/week_schedule_form.tsx, jupyterlab_gcpscheduler/src/components/scheduler_description.tsx, jupyterlab_gcpscheduler/src/components/scheduler_form.spec.tsx, jupyterlab_gcpscheduler/src/components/scheduler_form.tsx, jupyterlab_gcpscheduler/src/components/scheduler_widget.spec.tsx, jupyterlab_gcpscheduler/src/components/share_dialog.tsx, jupyterlab_gcpscheduler/src/components/submitted_job.spec.tsx, jupyterlab_gcpscheduler/src/components/submitted_job.tsx, jupyterlab_gcpscheduler/src/cron.spec.ts, jupyterlab_gcpscheduler/src/cron.ts, jupyterlab_gcpscheduler/src/data.ts, jupyterlab_gcpscheduler/src/interfaces.ts, jupyterlab_gcpscheduler/src/service/gcp.spec.ts, jupyterlab_gcpscheduler/src/service/gcp.ts, jupyterlab_gcpscheduler/src/test_helpers.ts
Dropped all uses of Job, in lieu of either Execution or Schedule
Title in submission dialog is dynamic based on the selected Type
screencast: http://go/scrcast/NjEwOTQ5NzYxOTY0NDQxNnw3ZmZiZDAzOC0xNg
mocks: http://slides/1Ce2_tF7xIV9_A-40dqbT0coejEAGRjmcwqmwysz6eSQ#slide=id.ga9ef7185fe_0_0
screenshot of submit button: https://screenshot.googleplex.com/dQuQrte6rgxMGwj (not sure why it showed up like that in the screencast)
=>  Update terms used in Scheduler UX

jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_editor_results.tsx
=> [BigQuery] Copy to DataFrame should support multiline queries

jupyterlab_bigquery/jupyterlab_bigquery/query_incell_editor.py, jupyterlab_bigquery/src/index.ts
This should the model not found bug
=> [BigQuery] Sync bigquery_query_incell_editor version between python and typescript

jupyterlab_bigquery/jupyterlab_bigquery/version.py, jupyterlab_bigquery/package.json, jupyterlab_bigquery/src/components/shared/bq_table.tsx
=> Revert div to fragment for BQTable scrolling; Update to bq 0.1.5

.github/workflows/presubmit.yaml, jupyterlab_vizier/src/service/vizier_service.ts
Also fixes minor lint error in Vizier service
=> Add presubmit config to run on all branches.

jupyterlab_bigquery/package.json, jupyterlab_bigquery/setup.py, jupyterlab_comments/package.json, jupyterlab_gcpscheduler/setup.py, jupyterlab_gcsfilebrowser/package.json, jupyterlab_gitsync/setup.py, jupyterlab_hwconfig/package.json, jupyterlab_hwconfig/setup.py, jupyterlab_ucaip/package.json, jupyterlab_ucaip/setup.py, jupyterlab_vizier/package.json, shared/gcp_jupyterlab_shared/handlers.py, shared/gcp_jupyterlab_shared/version.py, shared/package.json, shared/src/components/__snapshots__/icon_button_menu.spec.tsx.snap, shared/src/components/icon_button_menu.spec.tsx, shared/src/components/icon_button_menu.tsx, shared/src/components/icons.tsx, shared/src/components/learn_more_link.tsx, shared/src/components/message.tsx, shared/src/components/select_input.tsx, shared/src/components/text_input.tsx, shared/src/index.ts, shared/src/styles.ts
- This bumps the minor version of gcp_jupyterlab_shared since it introduces
a breaking change for jupyterlab_gcpscheduler.
- jupyterlab_gcpscheduler remains dependent on v1.0.x
=> Merges the changes to shared from new-scheduler branch.

jupyterlab_bigquery/jupyterlab_bigquery/list_items_handler/service.py
Allow Data Catalog to search public datasets
=> Allow public datasets to be searched via datacatalog api

jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx, jupyterlab_bigquery/src/components/list_items_panel/list_tree_item_widget.tsx, jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx, jupyterlab_bigquery/src/components/list_items_panel/service/bigquery_service.ts, jupyterlab_bigquery/src/components/list_items_panel/service/list_items.ts, jupyterlab_bigquery/src/index.ts
=> [BigQuery] Use server proxy to list project datasets.

jupyterlab_gcpscheduler/package.json, jupyterlab_gcpscheduler/src/components/__snapshots__/dialog.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/__snapshots__/job_list_item.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/__snapshots__/jobs_panel_widget.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/__snapshots__/share_dialog.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/__snapshots__/submitted_job.spec.tsx.snap, jupyterlab_gcpscheduler/src/components/dialog.tsx, jupyterlab_gcpscheduler/src/components/job_list_item.tsx, jupyterlab_gcpscheduler/src/components/jobs_panel_widget.tsx, jupyterlab_gcpscheduler/src/components/schedule_builder/hour_schedule_form.tsx, jupyterlab_gcpscheduler/src/components/scheduler_form.tsx, jupyterlab_gcpscheduler/src/components/share_dialog.tsx, jupyterlab_gcpscheduler/src/components/submitted_job.tsx, shared/gcp_jupyterlab_shared/version.py, shared/package.json, shared/src/components/checkbox_input.tsx
https://screencast.googleplex.com/cast/NjY0NzcwODQyNzIyMzA0MHxhZGRkMGNhNC03Zg
+ Fixed spacing in side bar header and view result button
+ dividers full length fix
+ week scheduler spacing fix
+ bump shared version
=> More UX fine tuning

jupyterlab_gcpscheduler/src/service/gcp.spec.ts, jupyterlab_gcpscheduler/src/service/gcp.ts, package-lock.json
This is a copy of #406 that fixes the failing test.
=> Order executions and schedules by name
