GoogleCloudPlatform/jupyter-extensions

setup.py

This makes installation a bit easier by allowing users to use
`pip install -e git+https://github.com/GoogleCloudPlatform/jupyter-gcs-contents-manager.git@master#egg=GcsContentsManager`

Add a minimal setup.py to support `pip install` directly from the repo

---

gcs_contents_manager.py

This change avoids loading the contents of all files under a directory when listing that directory. This is consistent with the behavior of the default FileContentsManager.
(https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L336)

Don't load file contents when getting a directory

---

gcs_contents_manager.py

This PR adds a feature where the GCS contents manager can run alongside the standard file-based contents manager.
This works by creating two virtual, top-level directories, `GCS` and `Local Disk`. The `GCS` directory maps to the GCS contents manager, and the `Local Disk` directory maps to the file-based contents manager.
That works well enough for reading and writing files from either GCS or local disk, but there is a subtle issue that can come up with JupyterLab if you use any widgets that use the FileBrowser's current path (such as the jupyterlab_git extension).
Those extensions might assume that the API paths being used map to an actual path on disk relative to the content manager's `root_dir` property.
To accommodate this, the `CombinedContentsManager` class has its own `root_dir` …

Support reading files from local disk

---

jupyter-gcs-contents-manager/Pipfile
jupyter-gcs-contents-manager/Pipfile.lock
jupyter-gcs-contents-manager/README.md
jupyter-gcs-contents-manager/gcs_contents_manager.py
jupyter-gcs-contents-manager/setup.py

- Moves the `jupyter-gcs-contents-manager` Python package to its own subfolder and runs `pyformat` over `gcs_contents_manager.py`.
- Adds `Pipenv` to assist with provisioning a local development environment.

Move GCS contents manager to subfolder

---

jupyterlab_gcedetails/src/components/details_dialog_body.tsx
jupyterlab_gcedetails/src/data.ts
jupyterlab_gcedetails/src/details_widget.spec.tsx
jupyterlab_gcedetails/src/details_widget.tsx

Restructuring the code for the GCE Details widget slightly by:
- Moving shared interfaces and constants into a data file (Details interface, Mapped attributes, Stylesheet)
- Extracting out the details dialog body component into its own file. This is the body of the dialog that appears when you click on the Vm status icon.
Originally this was all in the details widget file, restructuring so as we add more code to this folder it doesn't get too complicated.
Resolves #32

Restructuring code for GCE Details Widget

---

jupyterlab_bigquery/src/components/details_panel/dataset_details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/dataset_details_widget.tsx
jupyterlab_bigquery/src/components/details_panel/service/list_dataset_details.ts
jupyterlab_bigquery/src/components/details_panel/service/list_table_details.ts
jupyterlab_bigquery/src/components/details_panel/table_details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/table_details_widget.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx

As part of cleanup of initial commit for the BigQuery extension:
- removes console.log statements
- adds correct typing for dataset and table details
- requires double click rather than click to open details
Addresses this [task](https://b.corp.google.com/issues/159993668).

[BigQuery] fix details typing and remove console logs

---

jupyterlab_gcedetails/src/__snapshots__/details_widget.spec.tsx.snap
jupyterlab_gcedetails/src/components/chart_wrapper.tsx
jupyterlab_gcedetails/src/components/resource_utilization_charts.tsx
jupyterlab_gcedetails/src/components/widget_popup.tsx
jupyterlab_gcedetails/src/data.ts
jupyterlab_gcedetails/src/details_widget.tsx

A new icon should appear in the widget in the status bar, clicking on which displays a popup containing charts visualizing the memory and cpu usage:
Additionally, moved styling constants only used in certain files to those files, rather than exporting them from the data file.

[HardwareConfiguration] Added workflow to display utilization charts when widget is clicked

---

jupyterlab_bigquery/jupyterlab_bigquery/handlers.py
jupyterlab_bigquery/src/components/details_panel/service/list_table_details.ts
jupyterlab_bigquery/src/components/details_panel/table_details_panel.tsx

Adds more information for table schema (mode and description) and shows it in a more readable way. This is an intermediate step - a future PR will add further styling.

[BigQuery] Table schema formatting changes

---

jupyter-gcs-contents-manager/gcs_contents_manager.py

This change fixes a usability issue in the error message returned when a user of the CombinedContentsManager tries to save a file to the virtual, top-level directory.
Previously, that would result in a 404 error due to the contents manager not being able to find a nested contents manager for the top-level.
With this new change, it will return a 403 error saying the top-level is read-only

[jupyter-gcs-contents-manager] Improve error message for creating a file in the virtual top-level directory

---

.github/workflows/push.yaml

Addresses points in #81
This change will introduce a new **Postpush** workflow that runs when a new change is pushed to `master`.
When this action runs, three (3) artifacts will be produced which contain artifacts that can be uploaded to a release.
1. `gcp_jupyterlab_shared_server_<commit sha>` contains the shared Python package from the `shared` subfolder
1. `gcp_jupyterlab_shared_client_<commit sha>` contains the shared TS package from the `shared` subfolder
1. `jupyterlab_extensions_<commit sha>` is a zip folder comprised of the Python package from each `jupyter*` subfolder.
See https://github.com/prodonjs/jupyter-gcs-contents-manager/actions/runs/168631713 for an example

[Release] Add upload steps to collect artifacts from pushes

---

jupyterlab_bigquery/src/components/details_panel/dataset_details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/dataset_details_widget.tsx
jupyterlab_bigquery/src/components/details_panel/details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/service/list_dataset_details.ts
jupyterlab_bigquery/src/components/details_panel/service/list_table_details.ts
jupyterlab_bigquery/src/components/details_panel/table_details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/table_details_widget.tsx
jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab_widget.tsx

Small fixes:
- Corrects formatting for dataset default expiration and table expiration (previously showed dataset expiration as straight milliseconds and  table expiration as None)
- Shows empty schema message (previously would show empty table with headers)
- Removes unnecessary signals in `dataset_details_widget`, `table_details_widget`, and `query_editor_tab_widget`

[BigQuery] Fix dataset/table expiration and empty schema display

---

jupyterlab_bigquery/src/components/details_panel/dataset_details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx

In a [previous PR](https://github.com/GoogleCloudPlatform/jupyter-extensions/pull/99) I made just the schema scrollable, but since it is currently on the same panel as the details, the entire panel should be scrollable to account for smaller screens.

[BigQuery] Make entire details panel scrollable

---

jupyterlab_caip_optimizer/src/components/study_details.tsx
jupyterlab_caip_optimizer/src/components/suggest_trials/add_measurement_dialog.tsx
jupyterlab_caip_optimizer/src/components/suggest_trials/create_trial.tsx
jupyterlab_caip_optimizer/src/components/suggest_trials/index.spec.tsx
jupyterlab_caip_optimizer/src/components/suggest_trials/index.tsx
jupyterlab_caip_optimizer/src/components/suggest_trials/utils.ts
jupyterlab_caip_optimizer/src/service/optimizer.ts
jupyterlab_caip_optimizer/src/service/test-constants.ts
jupyterlab_caip_optimizer/src/store/studies.ts
jupyterlab_caip_optimizer/src/types.ts
jupyterlab_caip_optimizer/src/utils/urls.ts

- Updates add measurement component to allow for users to create intermediate measurements, not just final measurements.
- Adds the add measurement API call to redux to do the above.
- Updates custom trials component to submit fully completed trials (`COMPLETED` trial state) and request for a trial with parameters (`REQUESTED` trial state).
- Fixes API study config undefined response for `minValue`/`maxValue`  by defaulting them to `0`.
- **Request trial**
- **Add intermediate Measurement**

[Optimizer] update suggest trials for interval vizier team

---

jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx
jupyterlab_bigquery/src/components/list_items_panel/snackbar.tsx
jupyterlab_bigquery/src/reducers/index.ts
jupyterlab_bigquery/src/reducers/snackbarSlice.ts

Create snackbar to display error notifications, which can be called from anywhere in the extension using redux.
Use the snackbar to display errors when pinned projects have issues/permissions problems.

[BigQuery] Create snackbar for errors

---

jupyterlab_caip_optimizer/package.json
jupyterlab_caip_optimizer/src/components/create_study.spec.tsx

- Runs `jupyterlab_caip_optimizer` tests in series to prevent the asynchronous timeout error.
- Updated jest timeout to 10 seconds (default is 5 seconds) for the `Create Study Page > creates a study and redirects to the study details page` integration test

Fix integration tests failing due to asynchronous timeout

---

jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx
jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab.tsx
jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab_widget.tsx
jupyterlab_bigquery/src/components/shared/header.tsx
jupyterlab_bigquery/src/utils/widgetManager/widget_manager.ts

Allows user to open multiple editor windows from the sidebar (starter query `SELECT * FROM *`) or from the table details panel (starter query `SELECT * FROM table_id`).
New tabs are named `Query Editor 1`, `Query Editor 2`, etc; they continuously rise in number. It would be easy to add the ability to rename a tab, but not sure how that flow would look, so for now we'll just name them like 1,2,3...etc.

[BigQuery] Multiple full-window editors

---

jupyterlab_gcedetails/jupyterlab_gcedetails/handlers.py
jupyterlab_gcedetails/jupyterlab_gcedetails/handlers_test.py
jupyterlab_gcedetails/jupyterlab_gcedetails/test_data.py
jupyterlab_gcedetails/src/components/confirmation_page.tsx
jupyterlab_gcedetails/src/components/hardware_scaling_dialog.tsx
jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx
jupyterlab_gcedetails/src/data.ts

This commit:
- adds the confirmation page that appears in the hardware scaling dialog after the user submits the hardware scaling form
- modifies the server code to return gpu count as part of the details returned from nvidia-smi
- adds a HardwareConfiguration interface that represents a VM shape that the user can modify
- deletes some unused code (MASTER_TYPES)
Resolves #155

[HardwareConfiguration] Adding confirmation page before user submits VM reshaping request

---

jupyterlab_bigquery/package.json
jupyterlab_bigquery/src/components/query_editor/query_editor_incell/query_editor_incell.tsx
jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab.tsx
jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab_widget.tsx
jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx
jupyterlab_bigquery/style/index.css
package-lock.json

Uses resize signals from the full window widget and [react-resize-detector](https://www.npmjs.com/package/react-resize-detector) in the in-cell element to resize the query editor with `editor.layout()`. 
I was hoping to implement the resizing in both types of editor (both in-cell and full window) with widget signals, but I couldn't get it to work properly with the in-cell editor. However, it seems that react-resize-detector is fairly widely used and it includes a polyfill so that the resizing is compatible in most web browsers, so I feel ok about using it.
I'm wondering if we should convert the widget signal resizing to also use react-resize-detector just for consistency? Currently there is a slight delay in the in-cell editor resizing at times, so you will see a ghost of the old size for …

[BigQuery] Resize editor on side panel open and close

---

jupyterlab_bigquery/jupyterlab_bigquery/__init__.py
jupyterlab_bigquery/jupyterlab_bigquery/details_handler/__init__.py
jupyterlab_bigquery/jupyterlab_bigquery/details_handler/details_handler.py
jupyterlab_bigquery/jupyterlab_bigquery/tests/details_handlers_test.py
jupyterlab_bigquery/src/components/details_panel/details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/model_details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/model_details_widget.tsx
jupyterlab_bigquery/src/components/details_panel/service/list_model_details.ts
jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx
jupyterlab_bigquery/src/components/shared/striped_rows.tsx
jupyterlab_bigquery/src/components/shared/tabs.tsx

Adds extremely basic model details with description, labels, some metadata, and schema. Future steps include Training Options, and potentially the Training and Evaluation tabs for certain types of models.
Besides adding the model widget, this PR also pulls out shared components for striped rows and panel tabs.

[BigQuery] Add basic model details

---

jupyterlab_bigquery/src/components/list_items_panel/list_search_results.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_item_widget.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx
jupyterlab_bigquery/src/components/list_items_panel/search_bar.tsx
jupyterlab_bigquery/src/components/list_items_panel/service/list_items.ts
jupyterlab_bigquery/src/index.ts

Refactor the data tree in 'list_tree_item.tsx' and the search results in 'list_search_results.tsx'. The files now use class inheritance to be more self-contained and to prevent repetitive code between the files. Functionality of both files is identical to before refactoring (no features added).
Create refreshing feature for the data tree in 'list_tree_panel.tsx'. Refreshing can be triggered for the whole panel, or for individual projects/datasets via their context menu.
Also change header styling in 'list_tree_panel.tsx' to hide button overflow text with ellipsis instead of wrapping. Add tooltips to display the full title of buttons even when overflowed.

[BigQuery] Refactor tree and implement refreshing

---

jupyterlab_gcedetails/src/components/confirmation_page.tsx
jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx
jupyterlab_gcedetails/src/data.ts

This PR restricts the GPU types and counts a user can select from on the hardware scaling form:
- The attach GPU option is disabled if the user has selected an N1 general-purpose machine type
- Only the GPUs available in the user's project/zone are displayed as options
- Only the valid count values are displayed for the selected GPU type
- If fetching the available GPUs from gcloud fails falls back on to using the master GPU type and count lists as options in the dropdowns
https://screencast.googleplex.com/cast/NTUyNDMwNDcwNTg4MDA2NHwwZWQ1ZDg2ZC1iYQ
Resolves #154

[HardwareConfiguration] Restricting gpu types a user can select

---

jupyterlab_caip_optimizer/src/components/create_study/index.spec.tsx
jupyterlab_caip_optimizer/src/components/create_study/index.tsx
jupyterlab_caip_optimizer/src/components/create_study/parameter_list.tsx
jupyterlab_caip_optimizer/src/components/create_study/parameter_type_inputs.tsx
jupyterlab_caip_optimizer/src/components/create_study/types.ts
jupyterlab_caip_optimizer/src/components/create_study/utils.ts
jupyterlab_caip_optimizer/src/setupTests.ts
jupyterlab_caip_optimizer/src/types.ts

- User can enable a conditional parameter
- User then selects the parent parameter (only valid parameters are shown, ie can not be the current parameter, and must be a categorical, integer or discrete parameter spec)
- User then selects the valid options that the parameter shows up for
- **Should I show the parameter tree (like the one on the study details page)?** It would be easy for me to add.
**Boom - Created study!**

[Optimizer] create study conditional parameters

---

jupyterlab_bigquery/jupyterlab_bigquery/__init__.py
jupyterlab_bigquery/jupyterlab_bigquery/query_history_handler/__init__.py
jupyterlab_bigquery/jupyterlab_bigquery/query_history_handler/query_history_handler.py
jupyterlab_bigquery/jupyterlab_bigquery/tests/query_history_handler_test.py
jupyterlab_bigquery/src/components/details_panel/table_details_panel.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx
jupyterlab_bigquery/src/components/query_history/query_history_panel.tsx
jupyterlab_bigquery/src/components/query_history/query_history_widget.tsx
jupyterlab_bigquery/src/components/query_history/service/query_history.ts
jupyterlab_bigquery/src/components/shared/striped_rows.tsx

The user can click the 'Query History' button at the bottom of the side panel. This opens a new tab containing the query history.
The query history lists query jobs in reverse-chronological order, separated by date, which matches the the WebUI. Each query job includes its creation time, its success status, and its original query text.
Clicking on the list item for any query job will expand a details panel with all the information for that query. This detailed display matches the WebUI.
Co-authored-by: Heather Wing, Cynthia Jia

[BigQuery] Create query history feature

---

jupyterlab_gcedetails/src/components/action_bar.tsx
jupyterlab_gcedetails/src/components/confirmation_page.tsx
jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx
jupyterlab_gcedetails/src/components/machine_type_select.tsx
jupyterlab_gcedetails/src/components/select_input.tsx
jupyterlab_gcedetails/src/data.ts

- An update to the shared/action_bar.tsx file caused the buttons to overlap with the input on the hardware scaling form. Resolved this by creating an action_bar component specifically for gce_details (we were probably going to do this anyways because we need to add some more gce_details specific functionality to the action_bar):
- Testing the extension on a real Notebook Instance showed that the input labels incorporated from material-ui on the hardware scaling form were rendering strangely. Switched to using native labels for now - will look more into this if we decide we want to keep the material-ui labels:
Hardware scaling form with changes made in this commit:

[HardwareConfiguration] Fixing UI bugs

---

jupyterlab_bigquery/jupyterlab_bigquery/list_items_handler/service.py
jupyterlab_bigquery/jupyterlab_bigquery/tests/list_items_service_test.py
jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx
jupyterlab_bigquery/src/components/list_items_panel/service/list_items.ts
jupyterlab_bigquery/src/reducers/dataTreeSlice.ts
jupyterlab_bigquery/style/images/table_partitioned_18px.svg
jupyterlab_bigquery/style/index.css

Updates include:
- Add icons for partitioned tables
- Change the pin project button and the header display
- Fix the snackbar not displaying
- Fix unit test for searching
- Add 'Unpin project' option to project context menu
New icon for partitioned tables:
Minor changes to the header, including changing pin projects button to just an icon (confirmed with Huaiwei):
Fix problems with snackbar displaying incorrectly when pinning projects.
Fixed issues in unit tests for searching. All backend tests now pass.
New context menu option for projects:

[BigQuery] Side panel UI patches

---

jupyterlab_caip_optimizer/src/components/suggest_trials/add_measurement_dialog.tsx
jupyterlab_caip_optimizer/src/components/suggest_trials/create_trial.tsx
jupyterlab_caip_optimizer/src/utils/use_error_state_map.ts

Fixes add measurement and create custom trial dialogs not clearing input data after closing the dialog.
https://screencast.googleplex.com/cast/NjA0ODczMTQ4NzAxMDgxNnxjNmZjZDQwOS01NQ
https://screencast.googleplex.com/cast/NDkyMTMzNDcxNjk1NjY3MnxlMmZjNzFlZS1mOA

[Optimizer] fix dialogs not being cleared properly

---

jupyterlab_caip_optimizer/src/components/create_study/index.spec.tsx
jupyterlab_caip_optimizer/src/components/main_area_widget/index.spec.tsx
jupyterlab_caip_optimizer/src/components/main_area_widget/index.tsx
jupyterlab_caip_optimizer/src/components/parameter_spec_tree/common_node.ts
jupyterlab_caip_optimizer/src/components/parameter_spec_tree/index.tsx
jupyterlab_caip_optimizer/src/components/sidebar_widget/index.tsx
jupyterlab_caip_optimizer/src/components/snackbar_widget/index.spec.tsx
jupyterlab_caip_optimizer/src/components/snackbar_widget/index.tsx
jupyterlab_caip_optimizer/src/components/study_details/index.spec.tsx
jupyterlab_caip_optimizer/src/components/study_details/index.tsx
jupyterlab_caip_optimizer/src/components/suggest_trials/trials.tsx
jupyterlab_caip_optimizer/src/utils/theme.ts
jupyterlab_caip_optimizer/style/index.css

- Disables add measurement button for requested trials
- Fixes "trials not found" warning in tests for create study page
- Adds global material ui theme that uses Google Sans for headers
- Updates parameter tree to use material ui theme colors for vertices and connections

[Optimizer] Various changes

---

jupyterlab_gcedetails/src/components/confirmation_page.tsx
jupyterlab_gcedetails/src/components/details_dialog_body.tsx
jupyterlab_gcedetails/src/components/error_page.tsx
jupyterlab_gcedetails/src/components/hardware_configuration_dialog.tsx
jupyterlab_gcedetails/src/components/hardware_scaling_status.tsx
jupyterlab_gcedetails/src/data.ts
jupyterlab_gcedetails/src/service/notebooks_service.spec.ts
jupyterlab_gcedetails/src/service/notebooks_service.ts
shared/gcp_jupyterlab_shared/__init__.py
shared/package.json
shared/src/components/message.tsx

Adds error handling for when Notebook API calls fail:
- If  fails, the instance will be started and the user will be shown the error and the current state of their hardware configuration:
- https://screencast.googleplex.com/cast/NjMzNzE5NDM3NTUxMjA2NHxiZjc3OGMwZC0wZg
- If starting the machine fails, the user will be stuck on a dialog asking them to start their machine on the cloud console: 
- https://screencast.googleplex.com/cast/NTEzMjgxNjg5MzM0NTc5MnxhNGRlMDBiOC1hYw
We can decide on the styling we want for the dialog contents and update it in a different PR

[HardwareConfiguration] Adding error handling in rescaling dialog

---

jupyterlab_bigquery/jupyterlab_bigquery/query_history_handler/query_history_handler.py
jupyterlab_bigquery/jupyterlab_bigquery/tests/query_history_handler_test.py
jupyterlab_bigquery/package-lock.json
jupyterlab_bigquery/src/components/details_panel/details_panel.tsx
jupyterlab_bigquery/src/components/query_history/query_history_panel.tsx
jupyterlab_bigquery/src/components/query_history/service/query_history.ts
jupyterlab_bigquery/src/components/shared/read_only_editor.tsx
jupyterlab_bigquery/src/utils/formatters.ts
jupyterlab_bigquery/style/images/open_editor_20px.svg
jupyterlab_bigquery/style/images/open_editor_24px.svg
jupyterlab_bigquery/style/index.css

- Pulls out shared read-only editor (between details panel and expanded query history)
- Batches query history by date on the frontend with local timezone accounted for
- Can open old query in a full-window editor
- Adds indication of what caused an error for failed queries
- Adds extra test for query details with an error
A copy to clipboard button will be added in a future PR.
Successful query:
Failed query:

[BigQuery] Query history improvements

---

jupyterlab_bigquery/src/components/list_items_panel/list_search_results.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx

Fix how refreshing works at a global level:
- Refreshing all no longer deletes all pinned projects by resetting the side panel
- If no projects are pinned, refreshing re-retrieves the primary project of the notebook
- 'Refresh dataset' option removed from search result context menu

[BigQuery] Fix refreshing

---

jupyterlab_gcedetails/src/components/confirmation_page.tsx
jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx
jupyterlab_gcedetails/src/data.ts

Adding functionality to allow a user to remove GPUs. If the configuration originally had GPUs attached and he user unchecks the attachGPU checkbox a request will be made to the setAccelerator Notebooks API to set the accelerator to ACCELERATOR_UNSPECIFIED with count 0.

[HardwareConfiguration] Allow user to remove GPUs

---

jupyterlab_gcedetails/src/components/action_bar.tsx
jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx
jupyterlab_gcedetails/src/data.ts

Disables the submit button on the hardware scaling form if the user hasn't made any changes to their current configuration. Also changes the gpuType and gpuCount to always default to the first option when the attachGpu checkbox is checked.

[HardwareConfiguration] Disable submit reshaping if configuration is same

---

jupyterlab_bigquery/src/components/details_panel/dataset_details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx
jupyterlab_bigquery/src/components/query_editor/query_editor_incell/query_editor_incell.tsx
jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab.tsx
jupyterlab_bigquery/src/components/query_history/query_history_panel.tsx
jupyterlab_bigquery/src/components/shared/bq_table.tsx
jupyterlab_bigquery/src/components/shared/schema_table.tsx
jupyterlab_bigquery/src/components/shared/striped_rows.tsx

Changes all the fonts to roboto by importing them from the shared package. It may eventually make more sense to have an overall material UI theme and use a `ThemeProvider` rather than styling all the shared material UI components, but seeing as we have to set the font within each of the widgets already, it is a little simpler this way.

[BigQuery] Change fonts to roboto and pull out shared tables

---

jupyterlab_gcedetails/src/components/details_dialog_body.tsx

Before this change if a user clicked on the details icon while the details were being retrieved the extension would break. This fix displays a loading message while the details are being retrieved and disables the Update details button while the details are loading or if an error occurred while fetching the details.
https://screencast.googleplex.com/cast/NjQzNDYxMzAyNTA0NjUyOHwyNWY5N2MwYy0wNA

[HardwareConfiguration] Displaying loading page in dialog while details are being retrieved

---

jupyterlab_comments/src/components/code_review.tsx
jupyterlab_comments/src/components/comment.tsx
jupyterlab_comments/src/components/comment_context.tsx
jupyterlab_comments/src/components/comments_widget.tsx
jupyterlab_comments/src/components/new_comment_dialog.tsx
jupyterlab_comments/src/index.ts
jupyterlab_comments/src/service/file.ts
jupyterlab_comments/src/service/jupyterConfig.ts

- Add new command to FIleEditor's right click context menu that lets user add a new detached comment at the line number they have clicked on/highlighted
- Create new comment dialog widget that command uses
Also:
- Move Context interface containing labShell and docManager to jupyterConfig file
- Add missing unique keys for list item components

[Comments] add new comment with right-click file editor command

---

jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx

Removes uppercase text transform and changes some sizing.

[BigQuery] Small sidepanel styling changes to match mocks

---

jupyterlab_gcedetails/jupyterlab_gcedetails/handlers.py
jupyterlab_gcedetails/jupyterlab_gcedetails/handlers_test.py
jupyterlab_gcedetails/jupyterlab_gcedetails/test_data.py
jupyterlab_gcedetails/src/data/accelerator_types.ts
jupyterlab_gcedetails/src/details_widget.spec.tsx
jupyterlab_gcedetails/src/details_widget.tsx
jupyterlab_gcedetails/src/service/details_service.spec.ts
jupyterlab_gcedetails/src/service/details_service.ts
jupyterlab_gcedetails/src/test_helpers.ts

Removing the code to fetch the list of available GPUs using gcloud compute in the server and instead fetching them in the client using the Compute API.

[HardwareConfiguration] Fetching gpus from client

---

jupyterlab_gcedetails/src/components/__snapshots__/hardware_scaling_status.spec.tsx.snap
jupyterlab_gcedetails/src/components/error_page.tsx
jupyterlab_gcedetails/src/components/hardware_scaling_status.spec.tsx
jupyterlab_gcedetails/src/components/hardware_scaling_status.tsx
jupyterlab_gcedetails/src/components/instance_details_message.tsx
jupyterlab_gcedetails/src/service/details_service.spec.ts

Adding new instance details to the message displayed in the dialog once reshaping completes successfully. These details are already displayed in the error page so I'm moving the function that formats them out into it's own component to be used by both the error page and the completion message.

[HardwareConfiguration] Displaying instance details in reshape complete message

---

jupyterlab_bigquery/src/components/list_items_panel/list_search_results.tsx

Rather than a blank panel, now there is a message displayed when no search results arise.

[BigQuery] Show message when there are no search results

---

jupyterlab_gcedetails/src/components/server_wrapper.tsx
jupyterlab_gcedetails/src/details_widget.tsx
jupyterlab_gcedetails/src/index.ts

Currently service initialization happens after the first call to get details from the server as the project name, location, and instance name is needed to set up the services. Moving this to the root index file following the gcp_scheduler widget initialization pattern. If the getMetadata call fails then the error status is passed as props and the widget is launched in an error state.

[HardwareConfiguration] Moving service initialization to root

---

jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx
jupyterlab_bigquery/src/components/details_panel/table_details_widget.tsx
jupyterlab_bigquery/src/components/details_panel/table_preview.tsx
jupyterlab_bigquery/src/components/query_history/query_history_panel.tsx
jupyterlab_bigquery/src/components/shared/info_card.tsx

Pulls out the error box from query history and makes it a common component, `InfoCard`, reused for empty tables and partitioned tables.
`InfoCard` takes in a color, icon, message, and optional button, and displays the message along with matching color band and icon.

[BigQuery] Common info card

---

jupyterlab_bigquery/jupyterlab_bigquery/details_handler/service.py
jupyterlab_bigquery/jupyterlab_bigquery/tests/details_service_test.py

Adds a UTC timezone to `fromtimestamp`, which I didn't realize actually converts to local timezone by default rather than UTC. This will correct the training runs dropdown select dates.

[BigQuery] Fix timezone issue with fromtimestamp

---

jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx

Restricting user from attaching GPUs for instances with an R or Python based framework in the hardware scaling form.

[HardwareConfiguration] Restricting attaching GPU for incompatible frameworks

---

jupyterlab_gcedetails/src/components/hardware_scaling_form.tsx

Before this PR the extension would crash on the hardware scaling form when doing the framework-GPU compatibility check if a framework wasn't fetched with the GCE metadata. In production this shouldn't be an issue as we assume a framework should always be specified but for the sake of local testing I've added a fix that assumes the framework is compatible with attaching GPUs if a framework isn't specified.

[HardwareConfiguration] Fixing missing framework bug

---

jupyterlab_bigquery/jupyterlab_bigquery/list_items_handler/service.py
jupyterlab_bigquery/src/components/details_panel/model_details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx
jupyterlab_bigquery/src/components/details_panel/view_details_panel.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx
jupyterlab_bigquery/src/utils/starter_queries.ts

Makes boilerplate query through context menu available for all resources (previously unavailable for models and views), centralizes starter query text to the utils folder.

[BigQuery] Standardize starter queries

---

jupyterlab_bigquery/src/components/details_panel/details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/model_details_panel.tsx
jupyterlab_bigquery/src/components/details_panel/table_details_tabs.tsx
jupyterlab_bigquery/src/components/details_panel/table_preview.tsx
jupyterlab_bigquery/src/components/details_panel/view_details_panel.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx
jupyterlab_bigquery/src/components/list_items_panel/search_bar.tsx
jupyterlab_bigquery/src/components/loading_panel.tsx
jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab_widget.tsx
jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_editor_results.tsx
jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx
jupyterlab_bigquery/src/components/query_history/query_history_panel.tsx
jupyterlab_bigquery/src/components/query_history/query_history_widget.tsx
jupyterlab_bigquery/src/components/shared/bq_table.tsx
jupyterlab_bigquery/src/components/shared/info_card.tsx
jupyterlab_bigquery/src/components/shared/read_only_editor.tsx
jupyterlab_bigquery/src/components/shared/schema_table.tsx
jupyterlab_bigquery/src/components/shared/striped_rows.tsx
jupyterlab_bigquery/src/components/shared/styles.ts
jupyterlab_bigquery/src/components/shared/tabs.tsx
jupyterlab_bigquery/src/utils/dark_theme.ts
jupyterlab_bigquery/style/index.css

Initial version of dark mode. Most colors are set to jp variables (eg `jp-ui-font-color1`) which change automatically when the theme changes. For colors that don't match jp variables (google blue, red, green, and yellow), there is now a `gColor` function that reads the body attribute `data-jp-theme-light` and returns colors according to the [material style color guides](https://standards.google/guidelines/google-material/styles/color/#palettes).
An issue that still needs to be resolved: because we currently aren't listening to theme change signals, the editor will correctly initialize in a particular theme, but if you change the theme once it's loaded, it will not change accordingly. The user would have to open a new editor or refresh the window.

[BigQuery] Dark mode

---

jupyterlab_bigquery/jupyterlab_bigquery/list_items_handler/service.py
jupyterlab_bigquery/src/components/details_panel/view_details_panel.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx
jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab.tsx
jupyterlab_bigquery/src/components/query_editor/query_editor_tab/query_editor_tab_widget.tsx
jupyterlab_bigquery/src/utils/starter_queries.ts

When a view is in legacy sql, opening an editor from the details panel or context menu will ensure the editor is set to legacy sql as well.

[BigQuery] Support legacy sql

---

jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx
jupyterlab_bigquery/src/components/list_items_panel/list_tree_panel.tsx
jupyterlab_bigquery/src/components/list_items_panel/snackbar.tsx
jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx
jupyterlab_bigquery/src/components/shared/snackbar.tsx
jupyterlab_bigquery/src/reducers/snackbarSlice.ts

Adds a snackbar popup when a user copies from the context menu or from the query editor top bar. 
Alters the snackbar component - now you can pass in a duration in ms before the snackbar automatically disappears. The one that pops up after you copy something lasts for 2 seconds.

[BigQuery] Snackbar with autohide when copying

---

jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx
jupyterlab_bigquery/src/components/shared/bq_table.tsx

- Removes `scrollBeyondLastLine` which adds several lines at the end of the editor - this previously made scrolling difficult when trying to scroll past an in-cell editor within a notebook.
- Only shows pagination options if there are 10 rows in a query result or more.

[BigQuery] Editor tweaks

---

jupyterlab_bigquery/src/components/query_history/query_history_panel.tsx

Now when pressing the open query button on a past query, it prevents the `collapse` panel from also opening unnecessarily.

[BigQuery] Stop propagation on open query button in Query History

---

jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx

Adds a first context menu option to open the resource details.

[BigQuery] Add 'open details' context menu option

---

jupyterlab_bigquery/src/components/list_items_panel/list_tree_item.tsx

Previously if a user expanded a dataset, then collapsed the parent project and then re-opened that parent project, the previously open dataset would be stuck loading forever.
This fixes the issue by changing the initial loading state for dataset resources to `false` so that they will only be set to a loading status if they are actually fetching tables.

[BigQuery] Fix infinite loading when datasets are expanded, and project is collapsed and re-opened

---

jupyter-gcs-contents-manager/gcs_contents_manager.py

The default FileContentsManager decodes base64 files at save time (https://github.com/jupyter/notebook/blob/94af525a2c0aaa99311647c6cccf9add07a63033/notebook/services/contents/fileio.py#L334). This is important as files uploaded through the UI will be base64-encoded: the fact that we currently don't decode files before saving them to GCS means that Jupyter cannot later open these files.
For consistency with the Jupyter default contents manager, only decodes if the file is of type 'file'. This still works for uploading notebooks as the file type at first upload is always 'file'.

Fix handling of base64 files in GCSContentsManager

---

jupyterlab_gitsync/package-lock.json
jupyterlab_gitsync/package.json
jupyterlab_gitsync/src/components/git_setup/branch_setup.tsx
jupyterlab_gitsync/src/components/git_setup/path_setup.tsx
jupyterlab_gitsync/src/components/log_panel/sync_log.tsx
jupyterlab_gitsync/src/components/toolbar_buttons/control_button.tsx
jupyterlab_gitsync/src/components/toolbar_buttons/settings_button.tsx
jupyterlab_gitsync/src/components/toolbar_buttons/status_button.tsx
jupyterlab_gitsync/src/components/toolbar_buttons/sync_button.tsx
jupyterlab_gitsync/src/index.ts
jupyterlab_gitsync/src/service/git.ts
jupyterlab_gitsync/src/service/nbmerge_api.ts
jupyterlab_gitsync/src/service/notebook_file.ts
jupyterlab_gitsync/src/service/notebook_resolver.ts
jupyterlab_gitsync/src/service/service.ts
jupyterlab_gitsync/src/service/text_file.ts
jupyterlab_gitsync/src/service/text_resolver.ts
jupyterlab_gitsync/src/service/tracker.ts

**File Conflict Handling**
Change conflict handling implementation in preparation for file conflict ui component. The primary goal is to have a single event listener when the service has all file conflicts to avoid having to unnecessarily re-render components.
* `GitSyncService`:
* only emit `setupChange` if repo path changes (change how values are sent to listeners)
* add `blockedChange` signal to disable sync controls when conflicts occur
* automatic start of sync if sync was running before blocked state
* `FileTracker`: 
* checks for conflicts after reloading all files (instead of using listeners for individual files)
* emits conflict signal after checking all files (instead of emitting at the first file conflict)
* `TextFile & NotebookFile`: 
* add functions to open editor, view diff, …

[Git Sync] File Conflicts Handling

---

jupyterlab_gcpscheduler/README.md

Link to a publicly accessible version of the Scheduler user guide.

Fix link to user guide for Scheduler

---

jupyterlab_bigquery/src/components/query_editor/query_text_editor/query_text_editor.tsx
jupyterlab_bigquery/src/components/shared/bq_table.tsx

This was causing an error in the BQTable render method where each row is expected to be an array.

Fix issue where service worker result concats undefined.

---

jupyterlab_gcpscheduler/src/components/initialization/__snapshots__/initializer.spec.tsx.snap
jupyterlab_gcpscheduler/src/components/initialization/__snapshots__/service_statuses.spec.tsx.snap
jupyterlab_gcpscheduler/src/components/initialization/initializer.spec.tsx
jupyterlab_gcpscheduler/src/service/project_state.spec.ts
jupyterlab_gcpscheduler/src/service/project_state.ts
jupyterlab_gcpscheduler/src/test_helpers.ts

Currently, users trying to initialize the Scheduler get an error message
when deploying the Cloud Function. Unfortunately,  they are unable to proceed without manually enabling the Cloud Build API, deleting the Cloud Function, and then retrying the initialization steps.
This fix explicitly adds the Cloud Build API as a requirement when enabling the Scheduler for recurring runs.

Fix Cloud Function deployment issue by enabling Cloud Build

---

jupyterlab_bigquery/jupyterlab_bigquery/details_handler/service.py
jupyterlab_bigquery/setup.py

This change aligns the version of google-cloud-bigquery installed with the extension to AI Platform DLVM version and prevents errors on startup.

Revert google-cloud-bigquery to 1.26.1

---

scripts/build_jupyterlab.sh
scripts/common.sh

- The root causes appears to be an issue with Webpack transpiling the `highlight.js` module which is an indirect dependency of the uCAIP extension.
- Because this is not currently being offered for automated installation, we'll remove this temporarily from the `build_jupyterlab.sh` script.

Fix scripts to resolve presubmit issue

---

shared/gcp_jupyterlab_shared/handlers.py

This will allow SSL to succeed on certain systems like Macs while continuing to succeed on currently working systems

Add ssl option PROTOCOL_TLS to tornado HTTP requests

---

jupyter-gcs-contents-manager/gcs_contents_manager.py

This change avoids jupyter-server startup failure due to missing `preferred_dir` attribute after [this change](https://github.com/jupyter-server/jupyter_server/commit/2ca800829c96dc60893dc83715282b7b8fd03d59#diff-72888b4a95043904b226c1aa5addc9687a1dd09706da5e59ed28be58ae5f99c9R1829) in jupyter-server

Add 'preferred_dir' attribute to 'CombinedContentsManager'

---

kernels-mixer/setup.py

The new release version is `0.0.4`.
This also updates the `jupyter-server` dependency to `>=2.7.3`.
That is so users pick up the fix for
[this issue](https://github.com/jupyter-server/jupyter_server/issues/1299)

Create a new release for the `kernels-mixer` package.

---

kernels-mixer/kernels_mixer/websockets.py
kernels-mixer/setup.py

This provides more visibility to the user for the scenario that a client connection from the user has been established, but the Gateway connection to the backend kernel is still starting.

[kernels-mixer] Report an initial kernel status on websocket connections.

---

google-cloud-jupyter-config/google/cloud/jupyter_config/__init__.py
google-cloud-jupyter-config/google/cloud/jupyter_config/config.py
google-cloud-jupyter-config/google/cloud/jupyter_config/config_test.py
google-cloud-jupyter-config/google/cloud/jupyter_config/tokenrenewer.py
google-cloud-jupyter-config/setup.py

This change extends the `get_gcloud_config` method to reduce redundant invocations of `gcloud config config-helper`.
With this change, that subcommand will not be invoked more than once a minute, unless required in order to refresh credentials.
This change requires an additional dependency on the `cachetools` package.
Additionally, this change adds helper methods for getting the account and credentials that wrap the `get_gcloud_config` method.

[google-cloud-jupyter-config] Add caching to the gcloud config helpers.

---

kernels-mixer/kernels_mixer/kernels.py
kernels-mixer/kernels_mixer/kernels_test.py
kernels-mixer/kernels_mixer/kernelspecs.py
kernels-mixer/setup.py

The `MixingMappingKernelManager` and `MixingKernelSpecManager` classes have to bridge
between blocking and asynchronous versions of their underlying classes (blocking for
local kernels and asynchronous for remote kernels).
To do that bridging, they have to expose synchronous methods to callers that do
not support/expect the called methods to be asynchronous.
Previously, the `kernels-mixer` package tried to play it safe by making all of
the methods that have to bridge this difference be synchronous.
However, it turns out that approach causes issues with Tornado's event loop,
[which is single-threaded](https://www.tornadoweb.org/en/stable/guide/async.html#asynchronous-and-non-blocking-i-o).
I looked through the code for both `jupyter_server` and the underlying
`jupyter_client`, and it turns …

[kernels-mixer] Blocking logic cleanup/fixes.

---

google-cloud-jupyter-config/google/cloud/jupyter_config/config.py
google-cloud-jupyter-config/google/cloud/jupyter_config/config_test.py
google-cloud-jupyter-config/setup.py

The previous version of the async test case did not actually run to the end because we never awaited the result. That meant that we weren't actually testing the async behavior the way we thought we were and there were hidden bugs in it that were not caught by our tests.
This change fixes the test so that async test cases actually run end to end, and also fixes the preexisting bugs that were caught by the fixed tests.

[google-cloud-jupyter-config] Fix async test coverage and bugs this exposed.
